### PR TITLE
Remove SAS tests

### PR DESCRIPTION
**Pull request by hadley**
Because it appears that these files were created by haven and are not actually valid SAS files. They cause the development version of haven to error.

Would you mind merging and submitting to CRAN relatively quickly? Otherwise I'll need to hold off the haven release for a couple of weeks, and I'd love to get it out soon.

### CODE REVIEW

**Comment by btskinner** [comment]
@hadley, you're correct that I just created them with haven (I didn't have access to SAS at the time). When I have a chance, I'll try to create a set of test files using SAS and test with the new haven.

**Comment by hadley** [comment]
Great, thanks!  Are you ok with submitting to CRAN in the next couple of days? If so, I can start the CRAN submission process for haven.

**Comment by btskinner** [comment]
Just updated everything on my end and uploaded the new version to CRAN. Hopefully it'll go through that process quickly (don't see why it wouldn't).

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
